apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: pod-admission-webhook
  annotations:
    cert-manager.io/inject-ca-from: mpaas-webhooks/pod-admission-webhook-cert
webhooks:
- name: pod-admission-webhook.mpaas-webhooks.svc
  clientConfig:
    service:
      name: moperator
      namespace: default
      path: "/mutate--v1-pod"
  rules:
  - operations: ["CREATE"]
    apiGroups: [""]
    apiVersions: ["v1"]
    resources: ["pods"]
  failurePolicy: Ignore
  namespaceSelector:
    matchLabels:
      pod-admission-webhook-injection: enabled
  sideEffects: None
  admissionReviewVersions: ["v1"]